### ISSUE TITLE
Can't remove user

### ISSUE THREAD

**Issue by Poil** [claranet/ansible-role-users#15]
## Expected Behavior
We can't remove a user

## Current Behavior
State is not taken into account

## Possible Solution
Add 
```
state:  '{{ state|default("present") }}'
```

## Context
Delete a user that was created with ansible-roles-users

**Comment by ElieDeloumeau** [comment]
Hi, thanks for your useful issue!

Would you like to review this PR? https://github.com/claranet/ansible-role-users/pull/16
